version: "3"
services:
  namenode:
    image: hadoop3-ec
    hostname: namenode
    container_name: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    volumes:
      - ./data/:/data/

  datanode:
    image: hadoop3-ec
    command: ["hdfs", "datanode"]
    env_file:
      - ./config

  resourcemanager:
    image: hadoop3-ec
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./config

  nodemanager:
    image: hadoop3-ec
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config
